### ISSUE TITLE
Using these snippets in javascript scope

### ISSUE THREAD

**Issue by tnrich** [jorgeatgu/SVG-Snippets#3]
Do you know if there is a way to get this package's snippets to work in a .js scope?

I would like to use them with react.

Thanks very much!

**Comment by jorgeatgu** [comment]
Yes. You can modify the tag scope in every snippet. 

`<scope>text.html, text.xml, source.js</scope>`

This night i will update the package with this change ;)

**Comment by tnrich** [comment]
That would be sweet. Thanks!

**Comment by jorgeatgu** [comment]
Fixed. You can write SVG in React ;)
